---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ./authentik.yaml
- ./traefik.yaml
- ./traefik-forward-auth.yaml
- ./adguard.yaml
- ./hajimari.yaml
- ./galera.yaml
- ./plex.yaml
- ./sonarr.yaml
- ./sonarr-anime.yaml
- ./sonarr-remux.yaml
- ./radarr.yaml
- ./radarr-anime.yaml
- ./radarr-remux.yaml
- ./radarr-trailers.yaml
- ./overseerr.yaml
- ./home-automation.yaml
- ./mosquitto.yaml
- ./home-assistant.yaml
- ./esphome.yaml
- ./node-red.yaml
- ./rclone.yaml
- ./nginx.yaml
- ./uptime.yaml
- ./emqx.yaml
- ./jellyfin.yaml
- ./autoscan.yaml
- ./ytdl-sub.yaml
- ./prowlarr.yaml
- ./recyclarr.yaml
- ./sabnzbd.yaml
- ./wizarr.yaml
- ./ntpd.yaml
- ./aws-ddns.yaml
- ./piper.yaml
- ./whisper.yaml
- ./speedtest.yaml
- ./ladder.yaml
