---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces
- sealed-secrets
- flux
- cert-manager
- cloudnative-pg
- metallb
- netpol
- node-feature-discovery
- reloader
- intel-gpu-plugin
- longhorn-system
