---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  DOMAIN: nathanpawelek.com
  AWS_REGION: us-east-1
  METALLB_ADDR_RANGE: 192.168.0.10-192.168.0.19
  ADGUARD_LB: 192.168.0.10
  PLEX_LB: 192.168.0.11
  NTPD_LB: 192.168.0.12
  HOME_ASSISTANT_LB: 192.168.0.13
  MOSQUITTO_LB: 192.168.0.14
  TRAEFIK_LB: 192.168.0.15
  EMQX_LB: 192.168.0.16
  PROXY_LB: 192.168.0.17
  DERPNAS_ADDR: 192.168.0.150
  RACKNAS_ADDR: 192.168.0.151
  TIMEZONE: America/Chicago
  HTTP_PROXY: sabnzbd-proxy.sabnzbd.svc.cluster.local:8888
  NO_PROXY: .cluster.local,.nathanpawelek.com
